# Generated by Django 3.1 on 2021-04-09 01:36

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210407_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='phone',
        ),
        migrations.AddField(
            model_name='form',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
