# Generated by Django 3.1 on 2021-04-05 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('decription', models.CharField(max_length=150)),
                ('kpi', models.FileField(blank=True, upload_to='kpi')),
                ('schedule', models.FileField(blank=True, upload_to='schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
