# Generated by Django 3.1 on 2021-04-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='kpi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, primary_key=True, serialize=False),
        ),
    ]
